/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeekerMeRouteImport } from './routes/seeker/me'
import { Route as SeekerHomeRouteImport } from './routes/seeker/home'
import { Route as SeekerFeaturedRouteImport } from './routes/seeker/featured'
import { Route as SeekerApplicationsRouteImport } from './routes/seeker/applications'
import { Route as EmployerHomeRouteImport } from './routes/employer/home'
import { Route as EmployerHistoryRouteImport } from './routes/employer/history'
import { Route as EmployerCreditsRouteImport } from './routes/employer/credits'
import { Route as EmployerApplicationsRouteImport } from './routes/employer/applications'
import { Route as EmployerJobsIndexRouteImport } from './routes/employer/jobs/index'
import { Route as SeekerJobsIdRouteImport } from './routes/seeker/jobs.$id'
import { Route as EmployerJobsNewRouteImport } from './routes/employer/jobs/new'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerMeRoute = SeekerMeRouteImport.update({
  id: '/seeker/me',
  path: '/seeker/me',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerHomeRoute = SeekerHomeRouteImport.update({
  id: '/seeker/home',
  path: '/seeker/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerFeaturedRoute = SeekerFeaturedRouteImport.update({
  id: '/seeker/featured',
  path: '/seeker/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerApplicationsRoute = SeekerApplicationsRouteImport.update({
  id: '/seeker/applications',
  path: '/seeker/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerHomeRoute = EmployerHomeRouteImport.update({
  id: '/employer/home',
  path: '/employer/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerHistoryRoute = EmployerHistoryRouteImport.update({
  id: '/employer/history',
  path: '/employer/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerCreditsRoute = EmployerCreditsRouteImport.update({
  id: '/employer/credits',
  path: '/employer/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerApplicationsRoute = EmployerApplicationsRouteImport.update({
  id: '/employer/applications',
  path: '/employer/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsIndexRoute = EmployerJobsIndexRouteImport.update({
  id: '/employer/jobs/',
  path: '/employer/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerJobsIdRoute = SeekerJobsIdRouteImport.update({
  id: '/seeker/jobs/$id',
  path: '/seeker/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsNewRoute = EmployerJobsNewRouteImport.update({
  id: '/employer/jobs/new',
  path: '/employer/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/credits': typeof EmployerCreditsRoute
  '/employer/history': typeof EmployerHistoryRoute
  '/employer/home': typeof EmployerHomeRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/featured': typeof SeekerFeaturedRoute
  '/seeker/home': typeof SeekerHomeRoute
  '/seeker/me': typeof SeekerMeRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/seeker/jobs/$id': typeof SeekerJobsIdRoute
  '/employer/jobs/': typeof EmployerJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/credits': typeof EmployerCreditsRoute
  '/employer/history': typeof EmployerHistoryRoute
  '/employer/home': typeof EmployerHomeRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/featured': typeof SeekerFeaturedRoute
  '/seeker/home': typeof SeekerHomeRoute
  '/seeker/me': typeof SeekerMeRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/seeker/jobs/$id': typeof SeekerJobsIdRoute
  '/employer/jobs': typeof EmployerJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/credits': typeof EmployerCreditsRoute
  '/employer/history': typeof EmployerHistoryRoute
  '/employer/home': typeof EmployerHomeRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/featured': typeof SeekerFeaturedRoute
  '/seeker/home': typeof SeekerHomeRoute
  '/seeker/me': typeof SeekerMeRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/seeker/jobs/$id': typeof SeekerJobsIdRoute
  '/employer/jobs/': typeof EmployerJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/employer/applications'
    | '/employer/credits'
    | '/employer/history'
    | '/employer/home'
    | '/seeker/applications'
    | '/seeker/featured'
    | '/seeker/home'
    | '/seeker/me'
    | '/employer/jobs/new'
    | '/seeker/jobs/$id'
    | '/employer/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/employer/applications'
    | '/employer/credits'
    | '/employer/history'
    | '/employer/home'
    | '/seeker/applications'
    | '/seeker/featured'
    | '/seeker/home'
    | '/seeker/me'
    | '/employer/jobs/new'
    | '/seeker/jobs/$id'
    | '/employer/jobs'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/employer/applications'
    | '/employer/credits'
    | '/employer/history'
    | '/employer/home'
    | '/seeker/applications'
    | '/seeker/featured'
    | '/seeker/home'
    | '/seeker/me'
    | '/employer/jobs/new'
    | '/seeker/jobs/$id'
    | '/employer/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  EmployerApplicationsRoute: typeof EmployerApplicationsRoute
  EmployerCreditsRoute: typeof EmployerCreditsRoute
  EmployerHistoryRoute: typeof EmployerHistoryRoute
  EmployerHomeRoute: typeof EmployerHomeRoute
  SeekerApplicationsRoute: typeof SeekerApplicationsRoute
  SeekerFeaturedRoute: typeof SeekerFeaturedRoute
  SeekerHomeRoute: typeof SeekerHomeRoute
  SeekerMeRoute: typeof SeekerMeRoute
  EmployerJobsNewRoute: typeof EmployerJobsNewRoute
  SeekerJobsIdRoute: typeof SeekerJobsIdRoute
  EmployerJobsIndexRoute: typeof EmployerJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/me': {
      id: '/seeker/me'
      path: '/seeker/me'
      fullPath: '/seeker/me'
      preLoaderRoute: typeof SeekerMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/home': {
      id: '/seeker/home'
      path: '/seeker/home'
      fullPath: '/seeker/home'
      preLoaderRoute: typeof SeekerHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/featured': {
      id: '/seeker/featured'
      path: '/seeker/featured'
      fullPath: '/seeker/featured'
      preLoaderRoute: typeof SeekerFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/applications': {
      id: '/seeker/applications'
      path: '/seeker/applications'
      fullPath: '/seeker/applications'
      preLoaderRoute: typeof SeekerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/home': {
      id: '/employer/home'
      path: '/employer/home'
      fullPath: '/employer/home'
      preLoaderRoute: typeof EmployerHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/history': {
      id: '/employer/history'
      path: '/employer/history'
      fullPath: '/employer/history'
      preLoaderRoute: typeof EmployerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/credits': {
      id: '/employer/credits'
      path: '/employer/credits'
      fullPath: '/employer/credits'
      preLoaderRoute: typeof EmployerCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/applications': {
      id: '/employer/applications'
      path: '/employer/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof EmployerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/': {
      id: '/employer/jobs/'
      path: '/employer/jobs'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof EmployerJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/jobs/$id': {
      id: '/seeker/jobs/$id'
      path: '/seeker/jobs/$id'
      fullPath: '/seeker/jobs/$id'
      preLoaderRoute: typeof SeekerJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/new': {
      id: '/employer/jobs/new'
      path: '/employer/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  EmployerApplicationsRoute: EmployerApplicationsRoute,
  EmployerCreditsRoute: EmployerCreditsRoute,
  EmployerHistoryRoute: EmployerHistoryRoute,
  EmployerHomeRoute: EmployerHomeRoute,
  SeekerApplicationsRoute: SeekerApplicationsRoute,
  SeekerFeaturedRoute: SeekerFeaturedRoute,
  SeekerHomeRoute: SeekerHomeRoute,
  SeekerMeRoute: SeekerMeRoute,
  EmployerJobsNewRoute: EmployerJobsNewRoute,
  SeekerJobsIdRoute: SeekerJobsIdRoute,
  EmployerJobsIndexRoute: EmployerJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
