/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeekerMeRouteImport } from './routes/seeker/me'
import { Route as SeekerHomeRouteImport } from './routes/seeker/home'
import { Route as SeekerFeaturedRouteImport } from './routes/seeker/featured'
import { Route as SeekerFavoritesRouteImport } from './routes/seeker/favorites'
import { Route as SeekerApplicationsRouteImport } from './routes/seeker/applications'
import { Route as GuideRoleRouteImport } from './routes/guide.$role'
import { Route as EmployerMeRouteImport } from './routes/employer/me'
import { Route as EmployerHomeRouteImport } from './routes/employer/home'
import { Route as EmployerHistoryRouteImport } from './routes/employer/history'
import { Route as EmployerCreditsRouteImport } from './routes/employer/credits'
import { Route as EmployerApplicationsRouteImport } from './routes/employer/applications'
import { Route as EmployerJobsIndexRouteImport } from './routes/employer/jobs/index'
import { Route as SeekerJobsIdRouteImport } from './routes/seeker/jobs.$id'
import { Route as EmployerJobsNewRouteImport } from './routes/employer/jobs/new'
import { Route as EmployerHistoryDateRouteImport } from './routes/employer/history.$date'
import { Route as EmployerCreditsHistoryRouteImport } from './routes/employer/credits_.history'
import { Route as EmployerJobsEditIdRouteImport } from './routes/employer/jobs/edit.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerMeRoute = SeekerMeRouteImport.update({
  id: '/seeker/me',
  path: '/seeker/me',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerHomeRoute = SeekerHomeRouteImport.update({
  id: '/seeker/home',
  path: '/seeker/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerFeaturedRoute = SeekerFeaturedRouteImport.update({
  id: '/seeker/featured',
  path: '/seeker/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerFavoritesRoute = SeekerFavoritesRouteImport.update({
  id: '/seeker/favorites',
  path: '/seeker/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerApplicationsRoute = SeekerApplicationsRouteImport.update({
  id: '/seeker/applications',
  path: '/seeker/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoleRoute = GuideRoleRouteImport.update({
  id: '/guide/$role',
  path: '/guide/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerMeRoute = EmployerMeRouteImport.update({
  id: '/employer/me',
  path: '/employer/me',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerHomeRoute = EmployerHomeRouteImport.update({
  id: '/employer/home',
  path: '/employer/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerHistoryRoute = EmployerHistoryRouteImport.update({
  id: '/employer/history',
  path: '/employer/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerCreditsRoute = EmployerCreditsRouteImport.update({
  id: '/employer/credits',
  path: '/employer/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerApplicationsRoute = EmployerApplicationsRouteImport.update({
  id: '/employer/applications',
  path: '/employer/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsIndexRoute = EmployerJobsIndexRouteImport.update({
  id: '/employer/jobs/',
  path: '/employer/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerJobsIdRoute = SeekerJobsIdRouteImport.update({
  id: '/seeker/jobs/$id',
  path: '/seeker/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsNewRoute = EmployerJobsNewRouteImport.update({
  id: '/employer/jobs/new',
  path: '/employer/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerHistoryDateRoute = EmployerHistoryDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => EmployerHistoryRoute,
} as any)
const EmployerCreditsHistoryRoute = EmployerCreditsHistoryRouteImport.update({
  id: '/employer/credits_/history',
  path: '/employer/credits/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsEditIdRoute = EmployerJobsEditIdRouteImport.update({
  id: '/employer/jobs/edit/$id',
  path: '/employer/jobs/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/inquiry': typeof InquiryRoute
  '/notices': typeof NoticesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/credits': typeof EmployerCreditsRoute
  '/employer/history': typeof EmployerHistoryRouteWithChildren
  '/employer/home': typeof EmployerHomeRoute
  '/employer/me': typeof EmployerMeRoute
  '/guide/$role': typeof GuideRoleRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/favorites': typeof SeekerFavoritesRoute
  '/seeker/featured': typeof SeekerFeaturedRoute
  '/seeker/home': typeof SeekerHomeRoute
  '/seeker/me': typeof SeekerMeRoute
  '/employer/credits/history': typeof EmployerCreditsHistoryRoute
  '/employer/history/$date': typeof EmployerHistoryDateRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/seeker/jobs/$id': typeof SeekerJobsIdRoute
  '/employer/jobs/': typeof EmployerJobsIndexRoute
  '/employer/jobs/edit/$id': typeof EmployerJobsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/inquiry': typeof InquiryRoute
  '/notices': typeof NoticesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/credits': typeof EmployerCreditsRoute
  '/employer/history': typeof EmployerHistoryRouteWithChildren
  '/employer/home': typeof EmployerHomeRoute
  '/employer/me': typeof EmployerMeRoute
  '/guide/$role': typeof GuideRoleRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/favorites': typeof SeekerFavoritesRoute
  '/seeker/featured': typeof SeekerFeaturedRoute
  '/seeker/home': typeof SeekerHomeRoute
  '/seeker/me': typeof SeekerMeRoute
  '/employer/credits/history': typeof EmployerCreditsHistoryRoute
  '/employer/history/$date': typeof EmployerHistoryDateRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/seeker/jobs/$id': typeof SeekerJobsIdRoute
  '/employer/jobs': typeof EmployerJobsIndexRoute
  '/employer/jobs/edit/$id': typeof EmployerJobsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/inquiry': typeof InquiryRoute
  '/notices': typeof NoticesRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/employer/applications': typeof EmployerApplicationsRoute
  '/employer/credits': typeof EmployerCreditsRoute
  '/employer/history': typeof EmployerHistoryRouteWithChildren
  '/employer/home': typeof EmployerHomeRoute
  '/employer/me': typeof EmployerMeRoute
  '/guide/$role': typeof GuideRoleRoute
  '/seeker/applications': typeof SeekerApplicationsRoute
  '/seeker/favorites': typeof SeekerFavoritesRoute
  '/seeker/featured': typeof SeekerFeaturedRoute
  '/seeker/home': typeof SeekerHomeRoute
  '/seeker/me': typeof SeekerMeRoute
  '/employer/credits_/history': typeof EmployerCreditsHistoryRoute
  '/employer/history/$date': typeof EmployerHistoryDateRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
  '/seeker/jobs/$id': typeof SeekerJobsIdRoute
  '/employer/jobs/': typeof EmployerJobsIndexRoute
  '/employer/jobs/edit/$id': typeof EmployerJobsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/events'
    | '/faq'
    | '/inquiry'
    | '/notices'
    | '/onboarding'
    | '/reset-password'
    | '/terms'
    | '/employer/applications'
    | '/employer/credits'
    | '/employer/history'
    | '/employer/home'
    | '/employer/me'
    | '/guide/$role'
    | '/seeker/applications'
    | '/seeker/favorites'
    | '/seeker/featured'
    | '/seeker/home'
    | '/seeker/me'
    | '/employer/credits/history'
    | '/employer/history/$date'
    | '/employer/jobs/new'
    | '/seeker/jobs/$id'
    | '/employer/jobs/'
    | '/employer/jobs/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/events'
    | '/faq'
    | '/inquiry'
    | '/notices'
    | '/onboarding'
    | '/reset-password'
    | '/terms'
    | '/employer/applications'
    | '/employer/credits'
    | '/employer/history'
    | '/employer/home'
    | '/employer/me'
    | '/guide/$role'
    | '/seeker/applications'
    | '/seeker/favorites'
    | '/seeker/featured'
    | '/seeker/home'
    | '/seeker/me'
    | '/employer/credits/history'
    | '/employer/history/$date'
    | '/employer/jobs/new'
    | '/seeker/jobs/$id'
    | '/employer/jobs'
    | '/employer/jobs/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/events'
    | '/faq'
    | '/inquiry'
    | '/notices'
    | '/onboarding'
    | '/reset-password'
    | '/terms'
    | '/employer/applications'
    | '/employer/credits'
    | '/employer/history'
    | '/employer/home'
    | '/employer/me'
    | '/guide/$role'
    | '/seeker/applications'
    | '/seeker/favorites'
    | '/seeker/featured'
    | '/seeker/home'
    | '/seeker/me'
    | '/employer/credits_/history'
    | '/employer/history/$date'
    | '/employer/jobs/new'
    | '/seeker/jobs/$id'
    | '/employer/jobs/'
    | '/employer/jobs/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  InquiryRoute: typeof InquiryRoute
  NoticesRoute: typeof NoticesRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  EmployerApplicationsRoute: typeof EmployerApplicationsRoute
  EmployerCreditsRoute: typeof EmployerCreditsRoute
  EmployerHistoryRoute: typeof EmployerHistoryRouteWithChildren
  EmployerHomeRoute: typeof EmployerHomeRoute
  EmployerMeRoute: typeof EmployerMeRoute
  GuideRoleRoute: typeof GuideRoleRoute
  SeekerApplicationsRoute: typeof SeekerApplicationsRoute
  SeekerFavoritesRoute: typeof SeekerFavoritesRoute
  SeekerFeaturedRoute: typeof SeekerFeaturedRoute
  SeekerHomeRoute: typeof SeekerHomeRoute
  SeekerMeRoute: typeof SeekerMeRoute
  EmployerCreditsHistoryRoute: typeof EmployerCreditsHistoryRoute
  EmployerJobsNewRoute: typeof EmployerJobsNewRoute
  SeekerJobsIdRoute: typeof SeekerJobsIdRoute
  EmployerJobsIndexRoute: typeof EmployerJobsIndexRoute
  EmployerJobsEditIdRoute: typeof EmployerJobsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/me': {
      id: '/seeker/me'
      path: '/seeker/me'
      fullPath: '/seeker/me'
      preLoaderRoute: typeof SeekerMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/home': {
      id: '/seeker/home'
      path: '/seeker/home'
      fullPath: '/seeker/home'
      preLoaderRoute: typeof SeekerHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/featured': {
      id: '/seeker/featured'
      path: '/seeker/featured'
      fullPath: '/seeker/featured'
      preLoaderRoute: typeof SeekerFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/favorites': {
      id: '/seeker/favorites'
      path: '/seeker/favorites'
      fullPath: '/seeker/favorites'
      preLoaderRoute: typeof SeekerFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/applications': {
      id: '/seeker/applications'
      path: '/seeker/applications'
      fullPath: '/seeker/applications'
      preLoaderRoute: typeof SeekerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$role': {
      id: '/guide/$role'
      path: '/guide/$role'
      fullPath: '/guide/$role'
      preLoaderRoute: typeof GuideRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/me': {
      id: '/employer/me'
      path: '/employer/me'
      fullPath: '/employer/me'
      preLoaderRoute: typeof EmployerMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/home': {
      id: '/employer/home'
      path: '/employer/home'
      fullPath: '/employer/home'
      preLoaderRoute: typeof EmployerHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/history': {
      id: '/employer/history'
      path: '/employer/history'
      fullPath: '/employer/history'
      preLoaderRoute: typeof EmployerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/credits': {
      id: '/employer/credits'
      path: '/employer/credits'
      fullPath: '/employer/credits'
      preLoaderRoute: typeof EmployerCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/applications': {
      id: '/employer/applications'
      path: '/employer/applications'
      fullPath: '/employer/applications'
      preLoaderRoute: typeof EmployerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/': {
      id: '/employer/jobs/'
      path: '/employer/jobs'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof EmployerJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker/jobs/$id': {
      id: '/seeker/jobs/$id'
      path: '/seeker/jobs/$id'
      fullPath: '/seeker/jobs/$id'
      preLoaderRoute: typeof SeekerJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/new': {
      id: '/employer/jobs/new'
      path: '/employer/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/history/$date': {
      id: '/employer/history/$date'
      path: '/$date'
      fullPath: '/employer/history/$date'
      preLoaderRoute: typeof EmployerHistoryDateRouteImport
      parentRoute: typeof EmployerHistoryRoute
    }
    '/employer/credits_/history': {
      id: '/employer/credits_/history'
      path: '/employer/credits/history'
      fullPath: '/employer/credits/history'
      preLoaderRoute: typeof EmployerCreditsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/edit/$id': {
      id: '/employer/jobs/edit/$id'
      path: '/employer/jobs/edit/$id'
      fullPath: '/employer/jobs/edit/$id'
      preLoaderRoute: typeof EmployerJobsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EmployerHistoryRouteChildren {
  EmployerHistoryDateRoute: typeof EmployerHistoryDateRoute
}

const EmployerHistoryRouteChildren: EmployerHistoryRouteChildren = {
  EmployerHistoryDateRoute: EmployerHistoryDateRoute,
}

const EmployerHistoryRouteWithChildren = EmployerHistoryRoute._addFileChildren(
  EmployerHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  InquiryRoute: InquiryRoute,
  NoticesRoute: NoticesRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  EmployerApplicationsRoute: EmployerApplicationsRoute,
  EmployerCreditsRoute: EmployerCreditsRoute,
  EmployerHistoryRoute: EmployerHistoryRouteWithChildren,
  EmployerHomeRoute: EmployerHomeRoute,
  EmployerMeRoute: EmployerMeRoute,
  GuideRoleRoute: GuideRoleRoute,
  SeekerApplicationsRoute: SeekerApplicationsRoute,
  SeekerFavoritesRoute: SeekerFavoritesRoute,
  SeekerFeaturedRoute: SeekerFeaturedRoute,
  SeekerHomeRoute: SeekerHomeRoute,
  SeekerMeRoute: SeekerMeRoute,
  EmployerCreditsHistoryRoute: EmployerCreditsHistoryRoute,
  EmployerJobsNewRoute: EmployerJobsNewRoute,
  SeekerJobsIdRoute: SeekerJobsIdRoute,
  EmployerJobsIndexRoute: EmployerJobsIndexRoute,
  EmployerJobsEditIdRoute: EmployerJobsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
